/**
 * @desc Reducers Action List
 */

//Onboarding
export const SET_ONBOARDING_KYC = 'SET_ONBOARDING_KYC';
export const SET_ONBOARDING_LOADER = 'SET_ONBOARDING_LOADER';
export const SET_ONBOARDING_RES_ERROR = 'SET_ONBOARDING_RES_ERROR';
export const GET_ONBOARDING_RES_SUCCESS = 'GET_ONBOARDING_RES_SUCCESS';

// Auth
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_AUTH_VALIDATION_ERRORS = 'GET_AUTH_VALIDATION_ERRORS';
export const GET_AUTH_RES_ERROR = 'GET_AUTH_RES_ERROR';
export const GET_AUTH_RES_SUCCESS = 'GET_AUTH_RES_SUCCESS';
export const SET_AUTH_LOADER = 'SET_AUTH_LOADER';

//Portfolio
export const SET_PORTFOLIO_BALANCE_LIST = 'SET_PORTFOLIO_BALANCE_LIST';
export const SET_PORTFOLIO_LOADER = 'SET_PORTFOLIO_LOADER';
export const SET_PORTFOLIO_RES_ERROR = 'SET_PORTFOLIO_RES_ERROR';
export const GET_PORTFOLIO_RES_SUCCESS = 'GET_PORTFOLIO_RES_SUCCESS';

//Transaction
export const SET_TRANSACTION_LIST = 'SET_TRANSACTION_LIST';
export const SET_TRANSACTION_LOADER = 'SET_TRANSACTION_LOADER';
export const SET_TRANSACTION_RES_ERROR = 'SET_TRANSACTION_RES_ERROR';
export const GET_TRANSACTION_RES_SUCCESS = 'GET_TRANSACTION_RES_SUCCESS';

//Bank Accounts
export const SET_BANK_ACCOUNT_LIST = 'SET_BANK_ACCOUNT_LIST';
export const SET_BANK_ACCOUNT_LOADER = 'SET_BANK_ACCOUNT_LOADER';
export const SET_BANK_ACCOUNT_RES_ERROR = 'SET_BANK_ACCOUNT_RES_ERROR';
export const GET_BANK_ACCOUNT_RES_SUCCESS = 'GET_BANK_ACCOUNT_RES_SUCCESS';
export const SET_PLAID_CONFIGURATION = 'SET_PLAID_CONFIGURATION';

//Explore
export const SET_EXPLORE_LIST = 'SET_EXPLORE_LIST';
export const SET_EXPLORE_ITEM_DETAILS = 'SET_EXPLORE_ITEM_DETAILS';
export const SET_EXPLORE_LOADER = 'SET_EXPLORE_LOADER';
export const SET_EXPLORE_RES_ERROR = 'SET_EXPLORE_RES_ERROR';
export const GET_EXPLORE_RES_SUCCESS = 'GET_EXPLORE_RES_SUCCESS';
