export default {
  EmailList: 'EmailList',
  AccountModal: 'AccountModal',
  EmailDetails: 'EmailDetails',
  ComposeEmail: 'ComposeEmail',

  AllInboxesRoot: 'AllInboxesRoot',
  PrimaryRoot: 'PrimaryRoot',
  SocialRoot: 'SocialRoot',
  PromotionsRoot: 'PromotionsRoot',
  StarredRoot: 'StarredRoot',
  SnoozedRoot: 'SnoozedRoot',
  ImportantRoot: 'ImportantRoot',
  SentRoot: 'SentRoot',
  ScheduledRoot: 'ScheduledRoot',
  OutboxRoot: 'OutboxRoot',
  DraftsRoot: 'DraftsRoot',
  AllMailRoot: 'AllMailRoot',
  SpamRoot: 'SpamRoot',
  BinRoot: 'BinRoot',
  CalendarRoot: 'CalendarRoot',
  ContactsRoot: 'ContactsRoot',
  SettingsRoot: 'SettingsRoot',
  HelpAndFeedbackRoot: 'HelpAndFeedbackRoot',
  DrawerRoot: 'DrawerRoot',
  GeneralSettings: 'GeneralSettings',
};
